server:
  port: 8080

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true   #配置返回时间搓

#mybatis相关配置
mybatis:
  #当mybatis的xml文件和mapper接口不在相同包下时
  #需要用mapperLocations属性指定xml文件的路径。
  #*是个通配符，代表所有的文件，**代表所有目录下
  mapper-locations: classpath:mapper/*.xml
  #指定bean所在包
  #在mapper.xml中可以使用别名而不使用类的全路径名
  type-aliases-package: com.ifsaid.admin.entity

#pagehelper分页插件
pagehelper:
    helper-dialect: mysql
    reasonable: true
    params: count=countSql
    support-methods-arguments: true

jwt:
  header: jwtHeader
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N
  expiration: 3600000   #毫秒
  route:
    login: /auth/login
    refresh: /auth/refresh
    register: /auth/register

